version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.11.2
    working_directory: ~/circleci-demo-elixir-phoenix
    steps:
      - type: checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix do deps.get, compile --warnings-as-errors
  lint:
    docker:
      - image: circleci/elixir:1.11.2
    steps:
      - run: mix credo --strict
      - run: mix dialyzer --format short
  test:
    docker:
      - image: circleci/elixir:1.11.2
    steps:
      - test: mix do deps.get, compile --warnings-as-errors, mix test