version: 2.0
jobs:
  build:
	docker:
  	- image: circleci/elixir:1.11.2
	working_directory: ~/circleci-demo-elixir-phoenix
	steps:
  	- type: checkout
  	- run: mix local.rebar --force
  	- run: mix local.hex --force
  	- run: mix deps.get
  	- run: mix test
 